server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jt_security?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
